#!/usr/bin/env python

import sqlite3
import argparse

# con = sqlite3.connect("test.db")


def main():
    args = parse_arguments()

    print(args.subcommand)

    # if args.


print("Hello word")


def parse_arguments() -> any:
    parser = argparse.ArgumentParser()

    sub_parsers = parser.add_subparsers(dest="subcommand", required=True)

    add = sub_parsers.add_parser("add", help="Add new path")
    remove = sub_parsers.add_parser("remove", help="Remove path")

    list_paths = sub_parsers.add_parser("list", help="List paths")
    # list_paths.add_argument('')

    goto = sub_parsers.add_parser("goto", help="Go to path")
    goto.add_argument("path", help="Path")
    # parser_crazy.add_argument('--fool', action='store_const', const=True, help='it is foolish option')

    args = parser.parse_args()

    return args


if __name__ == "__main__":
    main()
