#!/usr/bin/env python

import time
import pathlib
import os.path
import inspect

from modules.sqlite import execute_db, get_cursor
from modules.parse_args import parse_arguments

src_file_path = inspect.getfile(lambda: None)
DB = os.path.dirname(src_file_path) + "test.db"


def main():
    args = parse_arguments()

    if args.subcommand == "setup":
        setup_db()
    elif args.subcommand == "add":
        add_path(args.path, args.label, args.alias)
    elif args.subcommand == "rm":
        remove_path(args.path_id, args.type)
    elif args.subcommand == "view":
        view_all_paths(args.showid)
    else:
        raise ValueError(f"Unknown subcommand: {args.subcommand}")


def setup_db():
    execute_db(DB, "CREATE TABLE path(id, label, path)")
    print(f"New db created in {DB}")


def remove_path(path_id: str, rm_type: "id|path|label" = "id"):
    print("Warning / FIXME: Removing broadly")
    c1 = execute_db(DB, f"DELETE FROM path WHERE id='{path_id}'")
    c2 = execute_db(DB, f"DELETE FROM path WHERE path='{path_id}'")
    c3 = execute_db(DB, f"DELETE FROM path WHERE label='{path_id}'")
    rm_count = c1 + c2 + c3
    print("rm count", rm_count)
    # print(c1, c2, c3)


# https://docs.python.org/3/library/sqlite3.html
def add_path(path: str, label: str, alias: str):
    my_id = time.time_ns()
    execute_db(
        DB, f"INSERT INTO path VALUES ('{my_id}', '{label}', '{path}', '{alias}')"
    )


def view_all_paths(show_id: bool = False):
    con = get_cursor(DB)
    res = con.execute("SELECT * FROM path")

    header = f"path\tlabel"
    divider = "-" * 20
    if show_id:
        header = "id\t" + header
        divider = "-" * 30

    print(header)
    print(divider)
    for row in res.fetchall():
        label = row[1]
        path = row[2]
        value_line = f"{path}\t{label}"
        if show_id:
            path_id = row[0]
            value_line = f"{path_id}\t" + value_line
        print(value_line)


if __name__ == "__main__":
    main()
